// export const GET_TOPIC_REQUEST = 'GET_TOPIC_REQUEST'
// export const GET_TOPIC_SUCCESS = 'GET_TOPIC_SUCCESS'
// export const GET_TOPIC_FAILURE = 'GET_TOPIC_FAILURE'
// export const GET_TOPIC_DETAIL_REQUEST = 'GET_TOPIC_DETAIL_REQUEST'
// export const GET_TOPIC_DETAIL_SUCCESS = 'GET_TOPIC_DETAIL_SUCCESS'
// export const GET_TOPIC_DETAIL_FAILURE = 'GET_TOPIC_DETAIL_FAILURE'
// export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
// export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
// export const USER_DETAIL_FAILURE = 'USER_DETAIL_FAILURE'
// export const HASNOT_READ_REQUEST = 'HASNOT_READ_REQUEST'
// export const HASNOT_READ_SUCCESS = 'HASNOT_READ_SUCCESS'
// export const HASNOT_READ_FAILURE = 'HASNOT_READ_FAILURE'



export const GET_WARE_SEARCH_REQUEST = 'GET_WARE_SEARCH_REQUEST'
export const GET_WARE_SEARCH_SUCCESS = 'GET_WARE_SEARCH_SUCCESS'
export const GET_WARE_SEARCH_FAILURE = 'GET_WARE_SEARCH_FAILURE'

export const SET_ITEMS_ONLINE_REQUEST = 'SET_ITEMS_ONLINE_REQUEST'
export const SET_ITEMS_ONLINE_SUCCESS = 'SET_ITEMS_ONLINE_SUCCESS'
export const SET_ITEMS_ONLINE_FAILURE = 'SET_ITEMS_ONLINE_FAILURE'

export const SET_ITEMS_OFFLINE_REQUEST = 'SET_ITEMS_OFFLINE_REQUEST'
export const SET_ITEMS_OFFLINE_SUCCESS = 'SET_ITEMS_OFFLINE_SUCCESS'
export const SET_ITEMS_OFFLINE_FAILURE = 'SET_ITEMS_OFFLINE_FAILURE'

export const SET_BATCH_ONLINE_REQUEST = 'SET_BATCH_ONLINE_REQUEST'
export const SET_BATCH_ONLINE_SUCCESS = 'SET_BATCH_ONLINE_SUCCESS'
export const SET_BATCH_ONLINE_FAILURE = 'SET_BATCH_ONLINE_FAILURE'

export const SET_BATCH_OFFLINE_REQUEST = 'SET_BATCH_OFFLINE_REQUEST'
export const SET_BATCH_OFFLINE_SUCCESS = 'SET_BATCH_OFFLINE_SUCCESS'
export const SET_BATCH_OFFLINE_FAILURE = 'SET_BATCH_OFFLINE_FAILURE'

export const SET_FILTER_ITEMS_REQUEST = 'SET_FILTER_ITEMS_REQUEST'
export const SET_FILTER_ITEMS_SUCCESS = 'SET_FILTER_ITEMS_SUCCESS'
export const SET_FILTER_ITEMS_FAILURE = 'SET_FILTER_ITEMS_FAILURE'

export const GET_SALE_DATA_REQUEST = 'GET_SALE_DATA_REQUEST'
export const GET_SALE_DATA_SUCCESS = 'GET_SALE_DATA_SUCCESS'
export const GET_SALE_DATA_FAILURE = 'GET_SALE_DATA_FAILURE'

export const GET_HOURLY_COST_REQUEST = 'GET_HOURLY_COST_REQUEST'
export const GET_HOURLY_COST_SUCCESS = 'GET_HOURLY_COST_SUCCESS'
export const GET_HOURLY_COST_FAILURE = 'GET_HOURLY_COST_FAILURE'

export const GET_SHOP_CAMPAGIN_REPORT_REQUEST = 'GET_SHOP_CAMPAGIN_REPORT_REQUEST'
export const GET_SHOP_CAMPAGIN_REPORT_SUCCESS = 'GET_SHOP_CAMPAGIN_REPORT_SUCCESS'
export const GET_SHOP_CAMPAGIN_REPORT_FAILURE = 'GET_SHOP_CAMPAGIN_REPORT_FAILURE'
